export const SET_FULL_NEWS_DATA = 'SET_FULL_NEWS_DATA';
export const HOME_API_CALL_BEGIN = 'HOME_API_CALL_BEGIN';
export const HOME_API_CALL_SUCCESS = 'HOME_API_CALL_SUCCESS';
export const HOME_API_CALL_FAILURE = 'HOME_API_CALL_FAILURE';
export const HOME_API_CALL_DISMISS_ERROR = 'HOME_API_CALL_DISMISS_ERROR';
